//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGrocery.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long Id { get; set; }
        public string CustomerCode { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public string VatNo { get; set; }
        public string CstNo { get; set; }
        public string TinNo { get; set; }
        public string PanNo { get; set; }
        public string GstNo { get; set; }
        public string ShippingContactNumber { get; set; }
        public string ShippingMobileNumber { get; set; }
        public string ShippingFaxNumber { get; set; }
        public string ShippingWhatsappNumber { get; set; }
        public string ShippingWebsiteUrl { get; set; }
        public string ShippingEmailAddress { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<int> ShippingCountryId { get; set; }
        public Nullable<int> ShippingStateId { get; set; }
        public Nullable<int> ShippingCityId { get; set; }
        public string ShippingPostalCode { get; set; }
        public string BillingContactNumber { get; set; }
        public string BillingMobileNumber { get; set; }
        public string BillingFaxNumber { get; set; }
        public string BillingWhatsappNumber { get; set; }
        public string BillingWebsiteUrl { get; set; }
        public string BillingEmailAddress { get; set; }
        public string BillingAddress { get; set; }
        public Nullable<int> BillingCountryId { get; set; }
        public Nullable<int> BillingStateId { get; set; }
        public Nullable<int> BillingCityId { get; set; }
        public string BillingPostalCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsPreferred { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual City City { get; set; }
        public virtual City City1 { get; set; }
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual State State { get; set; }
        public virtual State State1 { get; set; }
    }
}
