//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGrocery.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public long Id { get; set; }
        public string Barcode { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Mrp { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<int> MeasurementUnitId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string Photo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> SaleOnline { get; set; }
        public Nullable<bool> NotForSale { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual MeasurementUnit MeasurementUnit { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
